name: CI Workflow

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [debug, release]
        platform: [x64]
        depsrc: [none, contrib, system]
        cc: [gcc, clang]
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install booststrap's dependencies
      run: |
        sudo apt-get update 
        sudo apt-get -y install uuid-dev
    - name: Install dependencies
      if: matrix.depsrc == 'system'
      run: |
        sudo apt-get update 
        sudo apt-get -y install libcurl4-openssl-dev libzip-dev liblua5.3-dev
    - name: Build
      run: PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }} PREMAKE_OPTS="--lib-src=${{ matrix.depsrc }} --cc=${{ matrix.cc }}" ./Bootstrap.sh
    - name: Test
      run: bin/${{ matrix.config }}/premake5 test --test-all
    - name: Docs check
      run: bin/${{ matrix.config }}/premake5 docs-check
    - name: Upload Artifacts
      if: matrix.config == 'release' && matrix.depsrc == 'contrib' && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: premake-linux-${{ matrix.platform }}
        path: bin/${{ matrix.config }}/
